# Generated by Django 5.2.1 on 2025-05-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autor',
            new_name='autores',
        ),
    ]
